export const initialSiteConfig = {
  id: 'default',
  name: 'Pawan Tetgure',
  tagline: 'Video Editor & Motion Graphics Designer',
  heroTitleLine1: 'Video Editor &',
  heroTitleLine2: 'Motion Graphics',
  heroTitleLine3: 'Designer',
  heroDescription:
    'Elevating stories through precision editing, dynamic motion graphics, and cinematic storytelling. Based in Mumbai, available worldwide.',
  spotsText: 'Available for work • 3 spots left',
  showreelUrl: 'https://www.youtube.com/embed/TS01EZPkZ4Y?autoplay=1&rel=0',
  proofText: 'Trusted by <b>30+ creators & brands</b> worldwide',
  contactEmail: 'pawantetgure07@gmail.com',
  contactPhone: '+91 91727 68784',
  contactLocation: 'Mumbai, Maharashtra, India',
  socialLinks: {
    instagram: 'https://instagram.com/pawantetgure',
    youtube: 'https://youtube.com',
    linkedin: 'https://linkedin.com',
    twitter: 'https://twitter.com',
  },
};

export const initialProjects = [
  {
    id: 1,
    title: 'YouTube Showcase',
    category: 'YouTube',
    videoUrl: 'https://www.youtube.com/watch?v=MUopjdqDxBw',
    embedUrl: 'https://www.youtube.com/embed/MUopjdqDxBw?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/MUopjdqDxBw/hqdefault.jpg',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'High-Impact Visuals',
    category: 'Reels',
    videoUrl: 'https://www.youtube.com/watch?v=l_b1A2JPlRg',
    embedUrl: 'https://www.youtube.com/embed/l_b1A2JPlRg?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/l_b1A2JPlRg/hqdefault.jpg',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    title: 'Brand Film & Corporate',
    category: 'Corporate',
    videoUrl: 'https://www.youtube.com/watch?v=scy6nD1QozI',
    embedUrl: 'https://www.youtube.com/embed/scy6nD1QozI?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/scy6nD1QozI/hqdefault.jpg',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    title: 'Cinematic Travel Journey',
    category: 'Travel',
    videoUrl: 'https://www.youtube.com/watch?v=SzJZo3-vRVA',
    embedUrl: 'https://www.youtube.com/embed/SzJZo3-vRVA?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/SzJZo3-vRVA/hqdefault.jpg',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    title: 'Wedding Story Film',
    category: 'Wedding',
    videoUrl: 'https://www.youtube.com/watch?v=WLkyXm2-A5k',
    embedUrl: 'https://www.youtube.com/embed/WLkyXm2-A5k?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/WLkyXm2-A5k/hqdefault.jpg',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 6,
    title: 'Official Video Showreel',
    category: 'Showreel',
    videoUrl: 'https://www.youtube.com/watch?v=TS01EZPkZ4Y',
    embedUrl: 'https://www.youtube.com/embed/TS01EZPkZ4Y?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/TS01EZPkZ4Y/hqdefault.jpg',
    sortOrder: 6,
    isActive: true,
  },
];

export const initialReels = [
  {
    id: 1,
    title: 'Vertical Reel 1',
    videoUrl: 'https://www.youtube.com/shorts/eywjq1EJl6Y',
    embedUrl: 'https://www.youtube.com/embed/eywjq1EJl6Y?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/eywjq1EJl6Y/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'Vertical Reel 2',
    videoUrl: 'https://www.youtube.com/shorts/k3AuWYv-Boc',
    embedUrl: 'https://www.youtube.com/embed/k3AuWYv-Boc?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/k3AuWYv-Boc/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    title: 'Vertical Reel 3',
    videoUrl: 'https://www.youtube.com/shorts/I6XlBp_K_hQ',
    embedUrl: 'https://www.youtube.com/embed/I6XlBp_K_hQ?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/I6XlBp_K_hQ/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    title: 'Vertical Reel 4',
    videoUrl: 'https://www.youtube.com/shorts/HjerUrcbQbQ',
    embedUrl: 'https://www.youtube.com/embed/HjerUrcbQbQ?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/HjerUrcbQbQ/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    title: 'Vertical Reel 5',
    videoUrl: 'https://www.youtube.com/shorts/vOiVeAfVuRU',
    embedUrl: 'https://www.youtube.com/embed/vOiVeAfVuRU?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/vOiVeAfVuRU/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 6,
    title: 'Vertical Reel 6',
    videoUrl: 'https://www.youtube.com/shorts/Hs8RGt1xgPM',
    embedUrl: 'https://www.youtube.com/embed/Hs8RGt1xgPM?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/Hs8RGt1xgPM/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 7,
    title: 'Vertical Reel 7',
    videoUrl: 'https://www.youtube.com/shorts/8BEnUSzpMFM',
    embedUrl: 'https://www.youtube.com/embed/8BEnUSzpMFM?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/8BEnUSzpMFM/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 8,
    title: 'Vertical Reel 8',
    videoUrl: 'https://www.youtube.com/shorts/8rezB2kdN_M',
    embedUrl: 'https://www.youtube.com/embed/8rezB2kdN_M?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/8rezB2kdN_M/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 9,
    title: 'Vertical Reel 9',
    videoUrl: 'https://www.youtube.com/shorts/nM7dkbtJ9GM',
    embedUrl: 'https://www.youtube.com/embed/nM7dkbtJ9GM?autoplay=1&rel=0',
    thumbnailUrl: 'https://img.youtube.com/vi/nM7dkbtJ9GM/hqdefault.jpg',
    platform: 'youtube',
    badgeText: 'Shorts',
    sortOrder: 9,
    isActive: true,
  },
];

export const initialExperiences = [
  {
    id: 1,
    company: 'Alpha Beta Solutions',
    role: 'Video Editor & Motion Graphics Designer',
    duration: '2025 - Present',
    description:
      'Currently creating engaging videos and motion graphics across a range of client projects at this dynamic media company. I collaborate closely with creative teams and clients to deliver polished, visually compelling content — from concept through to final cut — always with a focus on storytelling and audience engagement.',
    skills: ['Premiere Pro', 'After Effects', 'Motion Graphics'],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    company: 'Mint Studio',
    role: 'Project Team Manager',
    duration: '2024 - 2025',
    description:
      'Led project teams across large-scale event productions, overseeing planning, execution, and delivery from end to end. I coordinated with creative directors and client stakeholders to ensure seamless workflows and consistently high-quality outputs. Notable brand collaborations included Godrej, Jio, Parimatch, WXM, Bombay Gymkhana, Raffles Hotel, The Grand Barso, Marsa Malaz Kempinski, Cipla, Kotak Mahindra Bank, HDFC Bank, Axis Bank, Sun Pharma, and Reliance — delivering successful, large-scale productions that sharpened my leadership and project management skills.',
    skills: ['Team Leadership', 'Event Management', 'Client Coordination'],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    company: 'Carpet Area',
    role: 'Video Editor & Motion Graphics Designer',
    duration: '2023 - 2024',
    description:
      'Worked closely with marketing and sales teams to produce visual content that showcased real estate developments in a clear and compelling way. I created promotional videos, property walkthroughs, and animated explainers that supported sales cycles, along with motion graphics for social media campaigns, branding materials, and investor presentations — all crafted in Adobe Premiere Pro, After Effects, and Photoshop.',
    skills: ['Real Estate', 'Property Videos', 'Social Media'],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    company: 'The Entertainment Factory',
    role: 'Video Editor & Motion Graphics Designer',
    duration: '2022 - 2023',
    description:
      'Handled end-to-end video editing for a wide range of branded and entertainment productions. I worked directly with directors and clients to craft sharp, engaging edits and motion graphics for high-visibility content. Projects included work for prominent personalities such as Ashish Vidyarthi, The Band of Boys, TEDx speakers, Kunal Kamra, Johnny Lever, and Sunil Grover — each delivered to a standard that contributed to strong viewership and audience engagement.',
    skills: ['Entertainment', 'Celebrity Content', 'TEDx'],
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    company: 'Freelance',
    role: 'Video Editor & Motion Graphics Designer',
    duration: 'Ongoing',
    description:
      'Independently collaborated with brands and influencers to produce creative video content for clients including Spotify, Mad Vision, and Matty Said That — turning briefs into visuals that genuinely connect with audiences. I also served as Concept and Visual Artist for Mumbai Cha Raja 2025, designing immersive 3D set installations at Lalbaug, Ganesh Galli — one of the most-watched Ganesh festival venues in Maharashtra.',
    skills: ['Freelance', '3D Set Design', 'Brand Content'],
    sortOrder: 5,
    isActive: true,
  },
];

export const initialReviews = [
  {
    id: 1,
    author: 'Rahul Desai',
    roleCompany: 'Head of Marketing, FinTech Startup · Mumbai',
    reviewText:
      'Honestly I wasn\'t expecting this level of quality for the budget. We gave them raw footage from our product launch event in BKC and they returned a 3-minute highlight reel that our CEO used in the board meeting. Everyone in the room asked who edited it. We\'ve been with Pawan Tetgure for 8 months now.',
    rating: 5,
    avatarBg: '#dbeafe',
    avatarInitials: 'R',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    author: 'Priya Malhotra',
    roleCompany: 'Founder, Luminos Skincare · Mumbai',
    reviewText:
      'The 3D product visualization they created for our skincare launch was genuinely jaw-dropping. We were comparing quotes from 4 agencies in Mumbai, Pawan Tetgure delivered the best work at almost half the price. The CGI ad ran on Meta and got a 4.2x ROAS in the first week.',
    rating: 5,
    avatarBg: '#fce7f3',
    avatarInitials: 'P',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    author: 'Sandeep Joshi',
    roleCompany: 'Director, SkyLine Realty · Mumbai',
    reviewText:
      'We needed a 3D walkthrough for our upcoming residential project in Powai before construction even started. Pawan Tetgure created a photorealistic environment that we literally used in the sales presentation. Bookings started coming in based on that video alone. This team understands real estate.',
    rating: 5,
    avatarBg: '#d1fae5',
    avatarInitials: 'S',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    author: 'Ananya Kulkarni',
    roleCompany: 'Co-Founder, Baaki D2C Brand · Pune',
    reviewText:
      'Hum ek D2C brand hain aur humne apne social media ke liye animated product explainer banwaya tha. Jo quality mili woh honestly premium agency jaisi thi lekin cost bohot reasonable thi. Delivery bhi time pe hui. Pawan Tetgure is now our go-to creative partner.',
    rating: 5,
    avatarBg: '#ede9fe',
    avatarInitials: 'A',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    author: 'Varun Nair',
    roleCompany: 'CEO, Learnly EdTech · Bangalore',
    reviewText:
      'They made an AI-generated brand video for our edtech platform using just our brand guidelines and a brief. No shoot, no crew, no location, just pure AI magic. The output looked like a proper ad film. Our cost savings vs a traditional production was around ₹2.5 lakhs. Unbelievable ROI.',
    rating: 5,
    avatarBg: '#fef9c3',
    avatarInitials: 'V',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 6,
    author: 'Nisha Arora',
    roleCompany: 'Event Director, Vogue Fests Mumbai · Mumbai',
    reviewText:
      'We organized a 2-day fashion event in Mumbai and needed a same-day edit for the second day\'s opening reel. I was nervous about the turnaround but they delivered a 90-second promo within 6 hours overnight. The crowd reaction when it played was incredible. Absolute professionals.',
    rating: 5,
    avatarBg: '#fde68a',
    avatarInitials: 'N',
    sortOrder: 6,
    isActive: true,
  },
];

export const initialFaqs = [
  {
    id: 1,
    question: 'What is your typical turnaround time for a video project?',
    answer:
      'For short-form content (Reels, TikToks, Shorts), turnaround is typically 24-48 hours. For standard YouTube edits or corporate videos, expect 3-5 business days. 3D animations and CGI commercials depend on complexity but typically take 7-14 days. Express same-day turnaround is available upon request.',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    question: 'How do we collaborate and share files?',
    answer:
      'We use Google Drive, Frame.io, or Dropbox for smooth file transfer. Frame.io allows you to comment timestamp-by-timestamp directly on the video review link so revisions are seamless and accurate.',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    question: 'What software and tools do you use?',
    answer:
      'Primary tools include Adobe Premiere Pro, After Effects, DaVinci Resolve Studio (Color Grading), Blender / Cinema 4D (3D animation & CGI), Photoshop, Illustrator, and leading AI enhancement suites.',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    question: 'How many revisions are included?',
    answer:
      'Every project includes 2 to 3 rounds of free revisions to ensure you get exactly the final polish you envision. Any minor tweaks or caption fixes are always complimentary.',
    sortOrder: 4,
    isActive: true,
  },
];

export const initialLogos = [
  { id: 1, name: 'PariMatch', imageUrl: '/assets/images/img_1.png', sortOrder: 1, isActive: true },
  { id: 2, name: 'Carpet Areas', imageUrl: '/assets/images/img_2.png', sortOrder: 2, isActive: true },
  { id: 3, name: 'Mumbai Cha Raja', imageUrl: '/assets/images/img_3.png', sortOrder: 3, isActive: true },
  { id: 4, name: 'Podar International School', imageUrl: '/assets/images/img_4.png', sortOrder: 4, isActive: true },
  { id: 5, name: 'Sahujii', imageUrl: '/assets/images/img_5.png', sortOrder: 5, isActive: true },
  { id: 6, name: 'SCT', imageUrl: '/assets/images/img_6.png', sortOrder: 6, isActive: true },
  { id: 7, name: 'Shoecase', imageUrl: '/assets/images/img_7.png', sortOrder: 7, isActive: true },
  { id: 8, name: 'WXM', imageUrl: '/assets/images/img_8.png', sortOrder: 8, isActive: true },
  { id: 9, name: 'Z24 Taas', imageUrl: '/assets/images/img_9.png', sortOrder: 9, isActive: true },
  { id: 10, name: 'Dotom', imageUrl: '/assets/images/img_19.png', sortOrder: 10, isActive: true },
  { id: 11, name: 'Fort Cha Raja', imageUrl: '/assets/images/img_20.png', sortOrder: 11, isActive: true },
  { id: 12, name: 'Godrej', imageUrl: '/assets/images/img_21.png', sortOrder: 12, isActive: true },
  { id: 13, name: 'HDFC Bank', imageUrl: '/assets/images/img_22.png', sortOrder: 13, isActive: true },
  { id: 14, name: 'Jio', imageUrl: '/assets/images/img_23.png', sortOrder: 14, isActive: true },
  { id: 15, name: 'MNG Group', imageUrl: '/assets/images/img_24.png', sortOrder: 15, isActive: true },
  { id: 16, name: 'SD Group', imageUrl: '/assets/images/img_25.png', sortOrder: 16, isActive: true },
  { id: 17, name: 'Shriji Sharan', imageUrl: '/assets/images/img_26.png', sortOrder: 17, isActive: true },
  { id: 18, name: 'WWD', imageUrl: '/assets/images/img_27.png', sortOrder: 18, isActive: true },
];

